### ISSUE TITLE
Shields don't work

### ISSUE THREAD

**Issue by crinkleskin** [bDekaru/ClassicDereth#2]
Major bug:

AL from shields doesn't seem to work at all making them completely useless. As a melee character this is game breaking for me considering how hard some things hit.

Also I don't think damage bonus from bows is being transferred to arrows although I need to do more testing with it to be sure.

**Comment by bDekaru** [comment]
There was some odd issue with shields not working from their creation until the server reset, and then they would start working. Not sure what's that about but I added a workaround until I get around to digging deeper on the issue.

The damage bonus from missile weapons weren't implemented, but I did that today as well.

**Comment by crinkleskin** [comment]
Amazing work. Thank you so much for the workaround!
